### ISSUE TITLE
Query multiple versions of Spore/Cluster cells

### ISSUE THREAD

**Issue by ShookLyngs** [sporeprotocol/spore-graphql#11]
Currently, spore-graphql only queries the latest version of the Spore/Cluster cells, filtered with the getSporeScript API. 
However, in reality, there could be multiple versions (v1/v2) of the scripts that need to be queried in the list.

**Comment by ShookLyngs** [comment]
A basic fix, but not fully tested yet: https://github.com/sporeprotocol/spore-graphql/commit/cbbfebfdae82da2be8acd634e07c085bf683b3cc

What's done:
- Implemented the multi-version spores/clusters querying feature
- Bumped lib/example dependencies

What's left:
- Added a filter input "codeHashes" in the graphql schema but not handled yet
- Need to do a full test on the changes
  - When querying a list from cells of multiple versions, the pagination might be buggy.

**Comment by ashuralyk** [comment]
> Added a filter input "codeHashes" in the graphql schema but not handled yet

any further description on this?

**Comment by ShookLyngs** [comment]
> any further description on this?

New filter input "codeHashes" added here: https://github.com/sporeprotocol/spore-graphql/pull/12/files#diff-160c34fe61acb6edcfc53a821f18efc0b0aa49a3a92582992f17338613d7204c.

The new input was supposed to help developer filter the exact versions of the spore/cluster cells.
But the feature was not implemented yet, so I think they can be removed for now, and added back in another PR.

**Comment by ashuralyk** [comment]
> > any further description on this?
> 
> New filter input "codeHashes" added here: https://github.com/sporeprotocol/spore-graphql/pull/12/files#diff-160c34fe61acb6edcfc53a821f18efc0b0aa49a3a92582992f17338613d7204c.
> 
> The new input was supposed to help developer filter the exact versions of the spore/cluster cells. But the feature was not implemented yet, so I think they can be removed for now, and added back in another PR.

we have `code_hash` args in `key` parameters, so I think it's the way we provide for users to distinguish different versions
